[package]
name = "laru"
version = "0.1.0"
edition = "2021"

[dependencies]
thirtyfour = "0.29.0"
thirtyfour_sync = "0.27.1"
thirtyfour_query = "0.6.1"
async-trait = "0.1"
tokio = "1.18.2"
serde_json = "1.0.81"

[dev-dependencies]
assert_matches = "1.5.0"
color-eyre = "0.5"
regex = "1"
